services:
  - type: web
    name: vinted-sticker-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
